### ISSUE TITLE
Team section images disappear when scrolling up

### ISSUE THREAD

**Issue by nurgul-ths** [Tech-Start-UCalgary/tsu-website#191] opened 2021-06-02 16:34 UTC
When scrolling up, the second row of the images disappears, leaving half the page empty. Should we change that?
https://user-images.githubusercontent.com/79397892/120517000-c8e64180-c3f1-11eb-92a5-9ef9422a0c6b.mov

**Comment by Niyousha99** [comment] 2021-06-04 19:46
Hi @nurgul-ths I have a PR open for changing the animation for the team section profiles. Once merged, can you check again and let me know if the problem is recurring?

**Comment by nurgul-ths** [comment] 2021-06-05 11:40
@Niyousha99 yep I can do that!

**Closed** 2021-06-25 13:06 UTC
Labels: question
